enable-ssh-support
ttyname $GPG_TTY
#default-cache-ttl 60 # 1 minute
default-cache-ttl 600 # 10 minutes
#default-cache-ttl 14400 # 4 hours
#max-cache-ttl 120 # 2 minutes
max-cache-ttl 7200 # 2 hours
#max-cache-ttl 86400 # 24 hours
write-env-file /Users/txc/.gnupg/gpg-agent-info
# -- macOS - Apple silicon (default /opt/homebrew/bin/pinentry)
#pinentry-program /opt/homebrew/bin/pinentry
#pinentry-program /opt/homebrew/bin/pinentry-curses
pinentry-program /opt/homebrew/bin/pinentry-mac
#pinentry-program /opt/homebrew/bin/pinentry-tty
# -- macOS - MacGPG2
#pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
