# Path to your Oh My Zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Required stuff, don't remove this.
export DOTFILES=${HOME}/.dotfiles
export ZSH_THEME="powerlevel10k/powerlevel10k"

# GPG configuration
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
: ${XDG_CACHE_HOME:=${HOME}/.cache}
[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ] && source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"

[ -f "${HOME}/.pythonrc" ] && export PYTHONSTARTUP="${HOME}/.pythonrc"

# Bootstrap prezto and configurations from ./zsh
[ -r "${DOTFILES}/zsh/bootstrap.zsh" ] && source "${DOTFILES}/zsh/bootstrap.zsh"

HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(macos git github oc kubectl docker sudo zsh-navigation-tools history history-substring-search)
#plugins=(macos git github oc kubectl docker sudo zsh-navigation-tools history history-substring-search)
plugins=(macos git gh oc kubectl docker sudo zsh-navigation-tools history history-substring-search)
plugins+=(helm)
#plugins+=(azure)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f "${DOTFILES}/zsh/.p10k.zsh" ]] || source "${DOTFILES}/zsh/.p10k.zsh"
